### ISSUE TITLE
When I set a different difficulty for each hole in the terminal room, I don’t know how to set the difficulty for CustomWarp: true of 2A or 5AB.

### ISSUE THREAD

**Issue by AAA1459** [rhelmot/CelesteRandomizer#136]

**Comment by rhelmot** [comment]
CustomWarps are assumed to be "free" transitions. If you need one of them to be gated by something, you should put it in a subroom, and add an internal edge between your subrooms which has requirements attached.

**Comment by AAA1459** [comment]
Ah thanks i get it
