### ISSUE TITLE
Impossible generation

### ISSUE THREAD

**Issue by uShldGetCeleste** [rhelmot/CelesteRandomizer#137]
Was playing with the randomizer and 6B but got stuck here. Supposed to go down but there's no way because of the jump through in the way

![image](https://user-images.githubusercontent.com/68669265/150613594-e1a8256b-52fd-4cd7-9513-c65073d6f1d0.png)
![image](https://user-images.githubusercontent.com/68669265/150613565-dedb6db1-ee12-4ccf-b2bd-5b40a41080a2.png)

**Comment by rhelmot** [comment]
```
Randomizer tip!

It is possible to clip downwards through one-way platforms using a feather or crusher block.
```
