### ISSUE TITLE
[feature] Debug command to change versions

### ISSUE THREAD

**Issue by Jeremy-Vidaurri** [rhelmot/CelesteRandomizer#180]
With the new addition of automated builds, it probably be possible to just add a debug command that allows users to update to either the current release, canary version (master branch), or PR version (given they provide the pr number).

Something like `rando_update <"release" | "canary" | "PR" | version number> [PR Number]`

**Comment by rhelmot** [comment]
Like, replace the entire mod with one downloaded from somewhere else? That's not a good idea, that's something that would get us flagged for malware behaviors.

**Comment by Jeremy-Vidaurri** [comment]
ah rip, that was what I was thinking. I took inspo from Portal 2's [Source Auto Record](https://github.com/p2sr/SourceAutoRecord/blob/9431178d0f2f30e1a620e573fdb07d677e79193a/src/Features/Updater.cpp) which utilizes the same concept.
