### ISSUE TITLE
Laundry can block the path in dashless where the button can't be hit. Going up through the heart route can lead to another laundry block.

### ISSUE THREAD

**Issue by masrock9** [rhelmot/CelesteRandomizer#27]

**Comment by rhelmot** [comment]
Can you post a seed where this happens? last I checked there wasn't any laundry in the heart route

**Comment by masrock9** [comment]
https://streamable.com/qary5e
Heres a rough recreation on a normal file. If I run into it again, I'll record the seed and post it here.

**Comment by rhelmot** [comment]
Yes, that's true, but the randomizer will never put something that could be blocked by laundry as an entrance. It doesn't have the logic in it to understand that those blocks can be removed, so it should never require the button to be pressed.

**Comment by masrock9** [comment]
That is odd. The clip is exactly what happened in a dashless run. If I run into it again, I'll report the seed.

**Comment by rhelmot** [comment]
I double checked and I forgot to mark the particular room you had trouble with as intraversable. ty for reporting!
