### ISSUE TITLE
Seeker slowdown is gone?

### ISSUE THREAD

**Issue by rhelmot** [rhelmot/CelesteRandomizer#33]

**Comment by DemoJameson** [comment]
SeekerSlowdown defaults to false in the custom map.
https://github.com/EverestAPI/Everest/blob/61c36ce7fec457358fa6bb2719d0db0c1a542901/Celeste.Mod.mm/Mod/Meta/MapMeta.cs#L354

**Comment by rhelmot** [comment]
ty for the pointer!!
