### ISSUE TITLE
Impossible dashless room

### ISSUE THREAD

**Issue by masrock9** [rhelmot/CelesteRandomizer#35]
Seed: 628318
Repeat on
Strange holes off
Pathway
Medium
Zero dashes
Perfect

Problem: Near the end, 04-c from Celestial Resort backwards isn't possible dashless.

**Comment by masrock9** [comment]
Addition: 

Seed: 628319
Repeat on
Strange holes off
Pathway
Medium
Zero dashes
Perfect

Problem: 04-d from Celestial Resort is impossible dashless.

**Comment by rhelmot** [comment]
I think I've fixed these for the next update.
