### ISSUE TITLE
b-02 from Mirror Temple B-Side

### ISSUE THREAD

**Issue by masrock9** [rhelmot/CelesteRandomizer#36]
The key door in the center of the room is problematic. A key is required later and this key door can take away the key when you don't want it to, making the map uncompletable.

Seed: 271828
Repeat on
Strange holes off
Pathway
Medium
Zero dashes
Perfect

**Comment by masrock9** [comment]
(Closed and reopened because I had misunderstood the problem but then realized a different problem)

**Comment by rhelmot** [comment]
will be solved by #32 when I get around to that
