### ISSUE TITLE
Need to add a DisableUpTransitions level attribute

### ISSUE THREAD

**Issue by AngellNick** [rhelmot/CelesteRandomizer#37]
Seed: 161803
Repeat: on
Holes: off
Logic: pathway
Length: medium
Dashes: zero
Difficulty: perfect

https://www.youtube.com/watch?v=gcBL4FEw_HM
In video, there is a loop which has a softlock. This isn't the way to go, but the rooms got close enough together to allow this to happen.
Also, last room is a heart room despite zero dashes. Area 3-CelestialResort/B/end/45

**Comment by rhelmot** [comment]
Yep... this is an issue. I've changed the title to reflect the thing that needs to be done to fix it.
