### ISSUE TITLE
Key Stuck in unobtainable position

### ISSUE THREAD

**Issue by LaurieDBunnykins** [rhelmot/CelesteRandomizer#38]
In Celestial Resort room 13-b, there is usually a Winged Berry hidden below spikes. In my most recent attempt at a randomizer (sadly did not think to check the seed until after I quit out), there was a key placed in this position, unobtainable without using Debug. Image below

https://imgur.com/Y6KPH2w

Blueye also experience an issue with an unobtainable key. The beginning of seed 86884 on Preset C requires you to complete Farewell Room d-02 to obtain a key, however, the room is stuck with electricity on, making the seed impossible almost immediately. Image of the debug map is below.

https://imgur.com/iFXLdt9

**Comment by rhelmot** [comment]
I fixed the latter issue this morning, it'll be in the next release. For the former issue, I believe it should have been fixed in version 0.2.2. Are you playing on a version lower than that?

**Comment by LaurieDBunnykins** [comment]
thanks for your response! yes, the former issue was performed before the release of version 0.2.2, and I have since updated to that version.
