### ISSUE TITLE
I spawned two Oshiros and I'm not sure how or why

### ISSUE THREAD

**Issue by paulmerritt** [rhelmot/CelesteRandomizer#40]
https://clips.twitch.tv/OutstandingSpicyDumplingsBrainSlug

Seed: 211077
Repeat: Off
Enter Strange Holes: On
Logic: Pathway
Length: Short
Dashes: One
Difficulty: Perfect

**Comment by rhelmot** [comment]
I fixed this a few minutes ago! it'll be in the next patch.
