### ISSUE TITLE
Is this room possible backwards?

### ISSUE THREAD

**Issue by paulmerritt** [rhelmot/CelesteRandomizer#41]
https://clips.twitch.tv/HardCloudyDiamondRlyTho 

The room is 7A-e-06/5

I transitioned into it from a gap covered by dust bunnies/spikes and then respawned at the far right.

I may be stupid, but I don't think this screen is possible backwards. Let me know

**Comment by rhelmot** [comment]
It is possible, but you need two dashes. This is a problem with the strange holes feature...

**Comment by rhelmot** [comment]
will be fixed in the next patch

**Comment by paulmerritt** [comment]
thank you god-dev
