### ISSUE TITLE
Stuck in the ceiling, random spawnpoint there

### ISSUE THREAD

**Issue by Blueye95** [rhelmot/CelesteRandomizer#47]
![image](https://user-images.githubusercontent.com/69042804/89103393-e7fef600-d411-11ea-89fa-2ee4bb6e6a70.png)
seed 124, ruleset C
Forsaken city A, room 5
Had to debug out to keep moving (or reset chapter)

**Comment by rhelmot** [comment]
oops, that's a mistake on my part. Fixed!
