### ISSUE TITLE
Madeline can leave room through upper holes and stand on top of them

### ISSUE THREAD

**Issue by amellensatz** [rhelmot/CelesteRandomizer#51]
Version: 0.3.1
Ruleset A
seed: azxtvy
hash: 3466357447
room: Celeste/4-GoldenRidge/A/c-06/6

Madeline can go up through the top hole and walk around on top of the room; I wouldn't expect this to be possible.

**Comment by rhelmot** [comment]
Thanks for reporting. Fixed!
