### ISSUE TITLE
Resort A 0x-a right entry softlock

### ISSUE THREAD

**Issue by Blueye95** [rhelmot/CelesteRandomizer#52]
![image](https://user-images.githubusercontent.com/69042804/89123584-cadd2c80-d4d0-11ea-85f5-9e2931ed51bd.png)
 
![image](https://user-images.githubusercontent.com/69042804/89123606-e34d4700-d4d0-11ea-958e-45678cd90e9f.png)
Ruleset A, version 0.31

**Comment by rhelmot** [comment]
fixed, lol
