### ISSUE TITLE
Wind SFX missing?

### ISSUE THREAD

**Issue by UltraMarlin** [rhelmot/CelesteRandomizer#54]
Where did they go? Why only sometimes? Is this because of randomized ambience?

Who will tell us?

**Comment by DemoJameson** [comment]
Maybe this should be addressed via Everest. So Modder doesn't have to deal with it.
https://github.com/max4805/Everest-ExtendedVariants/blob/495796772be2c62c6643d7f43eeb6916a734cdba/ExtendedVariantMode/Variants/WindEverywhere.cs#L90

**Comment by rhelmot** [comment]
concerning. sometimes modding this game feels like prodding around in the dark with a stick.
