### ISSUE TITLE
Documentation on the "enter strange holes" feature?

### ISSUE THREAD

**Issue by amellensatz** [rhelmot/CelesteRandomizer#55]
Most of the randomizer options are self-explanatory, but this one is confusing.  It would be nice to know what this switch does - in particular, any (lack of) guarantees on whether the resulting maps will be possible to complete, and whether an impossible map generated with it is considered a bug or not.  Thanks!

**Comment by rhelmot** [comment]
![image](https://user-images.githubusercontent.com/2498805/89152026-14506a80-d517-11ea-90d2-2a02f3f49b7b.png)

**Comment by rhelmot** [comment]
whether issues arising from it constitute bugs is honestly still up in the air. I'll fix whatever I can, and I have been able to fix most of the strange holes issues people have reported, so I think "doesn't make sense" is the best I can fit in a two line description for now.
