### ISSUE TITLE
Game crashes when use ctrl+right click to teleport on debug map.

### ISSUE THREAD

**Issue by DemoJameson** [rhelmot/CelesteRandomizer#79]
No problem with the first random map after game launches. On the second random map it causes the game to crash, because AreaData.Get(areaKey) is null.

[log.txt](https://github.com/rhelmot/CelesteRandomizer/files/5084248/log.txt)

**Comment by rhelmot** [comment]
Fixed. Arguably this is a bug in everest for not considering the SID when comparing two AreaKey values with ==.
