### ISSUE TITLE
Randomizer chapter complete information showing on collab map end screen

### ISSUE THREAD

**Issue by tcookiem** [rhelmot/CelesteRandomizer#95]
The information for an unfinished randomizer run showed up on the chapter complete screen on top of the collab map information: https://cdn.discordapp.com/attachments/738558439227392082/757136535396155473/celeste_screenshot.png

Steps to reproduce:
- Load into a randomizer run
- Quit randomizer
- Enter collab file with "Display End Screen For All Maps" turned on
- Enter collab level
- Complete collab level

**Comment by tcookiem** [comment]
I just had it happen again but I'd finished the randomizer run and it still displayed the info from the end of it

**Comment by rhelmot** [comment]
Fixed! This was an issue that had to do with how I persisted the ending metadata while the endless mode was making a new level. It would have also been an issue if you had finished farewell after playing the randomizer.
